name: code2md

options:
  bundleIdPrefix: xyz.billchiu
  deploymentTarget:
    macOS: "14.0"

targets:
  code2md:
    type: application
    platform: macOS

    sources:
      - path: code2md
        type: group

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: xyz.billchiu.code2md
        MARKETING_VERSION: "1.1.1"
        CURRENT_PROJECT_VERSION: "21"
        SWIFT_VERSION: "5.9"
        ENABLE_APP_SANDBOX: NO
        ARCHS: "$(ARCHS_STANDARD)"

    info:
      path: code2md/Info.plist
      properties:
        CFBundleName: code2md
        CFBundleDisplayName: code2md
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSApplicationCategoryType: public.app-category.developer-tools
        NSSupportsAutomaticGraphicsSwitching: true
        # File types
        CFBundleDocumentTypes:
          - CFBundleTypeName: Folder
            CFBundleTypeRole: Viewer
            LSItemContentTypes:
              - public.folder
            LSHandlerRank: Alternate

          - CFBundleTypeName: Any File
            CFBundleTypeRole: Viewer
            LSItemContentTypes:
              - public.item
            LSHandlerRank: Alternate
